using Avalonia;

namespace PZ.RxAvalonia;


public static class ComponentExtensions
{
    /// <summary>
    /// Used by autogenerated extensions from source generator for direct apply value to component's property
    /// </summary>
    /// <typeparam name="TControl"></typeparam>
    /// <param name="control"></param>
    /// <param name="setAction"></param>
    /// <returns></returns>
    public static TControl _setCommonEx<TControl>(this TControl control, Action setAction)
        where TControl : AvaloniaObject
    {
        setAction();
        if (control is IDeclarativeComponent component)
            component.UpdateState();
        return control;
    }
}
